name: medminder
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  nfc_manager: ^3.5.0
  flutter_local_notifications: ^9.9.1
  flutter_blue: ^0.8.0
  wifi_iot: ^0.3.19+1
  sqflite: ^2.4.1
  path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
