name: medminder
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  core_data: ^0.1.0
  nfc_manager: ^2.0.0
  flutter_local_notifications: ^9.0.0
  bluetooth: ^0.7.0
  wifi: ^0.1.0
  sqflite: ^2.0.0+4
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
